apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-logger
  template:
    metadata:
      labels:
        app: http-logger
    spec:
      containers:
      - name: http-logger
        image: recrutaz/http-logger:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: http-logger-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: http-logger
